services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    networks:
      - pg-network
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: popcorn@palace.com
      PGADMIN_DEFAULT_PASSWORD: popcorn-palace
    ports:
      - "5050:80"
    networks:
      - pg-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    build: .
    container_name: popcorn-palace-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/popcorn-palace
      SPRING_DATASOURCE_USERNAME: popcorn-palace
      SPRING_DATASOURCE_PASSWORD: popcorn-palace
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres: